<?php

/**
 * @file
 * This module provides student information.
 */

/**
 * Implements hook_permission().
 */
function student_permission() {
  return array(
    'administer my module' => array(
      'title' => t('Administer my module'),
      'description' => t('Perform administration tasks for my module.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function student_menu() {
  $items = array();
  $items['student'] = array(
    'title' => 'Student Registration Form',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('student_form'),
    'access callback' => 'admin_role',
    'access arguments' => array('administer my module'),
    'file' => 'student.admin.inc',
  );
  $items['student/records'] = array(
    'title' => 'StudentRecords',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer my module'),
    'page callback' => 'student_list',
    'access callback' => 'admin_role',
    'file' => 'student.admin.inc',
  );
  $items['student/records/%/delete'] = array(
    'title' => 'StudentRecords',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer my module'),
    'page callback' => 'student_form_delete',
    'page argument' => array(3),
    'access callback' => TRUE,
    'file' => 'student.admin.inc',
  );
  $items['student/records/%/edit'] = array(
    'title' => 'StudentRecords',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer my module'),
    'page arguments' => array('student_edit_form'),
    'page argument' => array(3),
    'access callback' => TRUE,
    'file' => 'student.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_role().
 */
function admin_role() {
  global $user;
  if (in_array('administrator', $user->roles)||(in_array('manager', $user->roles))) {
    return TRUE;
  }
}
